os: linux
dist: xenial
language: python
python: 3.6

install:
  - pip install pylint
  - pip install -r requirements.txt

script:  
  - pylint info_cluster setup.py
  - python setup.py install
  - python info_cluster/test_info_cluster.py

deploy:
  provider: pypi
  user: zhaofeng-shu33
  password: $TWINE_PASSWORD
  on:
    tags: true