os: linux
dist: xenial
language: python
python: 3.6

install:
  - pip install pylint
  - pip install -r info_cluster/requirements.txt

script:
  - pylint info_cluster setup.py
  - python setup.py install
