matrix:
  include: 
  - os: linux
    dist: xenial
    sudo: required
    services: docker
    env: DOCKER_IMAGE=zhaofengshu33/lemon:v2
         PLAT=manylinux2010_x86_64
  - os: osx
    osx_image: xcode9.4
    sudo: required
    addons:
      homebrew:
        taps: zhaofeng-shu33/liblemonformula
        packages:
          - liblemon
  - os: osx
    osx_image: xcode10.2 
    sudo: required
    addons:
      homebrew:
        taps: zhaofeng-shu33/liblemonformula
        packages:
          - liblemon

# - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-all-dev; fi
# build and install gtest library manually    

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo python -m pip install cmake; fi
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  - make
  - cd .. 

install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      sudo python3 -m pip install twine wheel cython
      python3 setup.py bdist_wheel
      python3 -m twine upload dist/* -u zhaofeng-shu33 && echo success || echo "upload failed"
    fi    
script:
# used for testing
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      python -m pip install twine
      docker run --rm -e PLAT=$PLAT -v `pwd`:/code $DOCKER_IMAGE /bin/bash -c 'cd /code; ./build.sh'
      python -m twine upload dist/wheelhouse/*.whl -u zhaofeng-shu33 && echo success || echo "upload failed"
    fi
