version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x64
environment:
  VCPKG_ROOT: C:\Tools\vcpkg
  Python3_ROOT_DIR: C:\Python36-x64
install:
- cmd: >-

    git submodule update --init --recursive

    IF NOT EXIST "C:\Tools\vcpkg\installed\x64-windows\include\lemon\core.h" vcpkg install liblemon:x64-windows

    curl https://gitee.com/freewind201301/appveyor-patch-liblemon/raw/master/preflow.h -o preflow.h
    
    copy preflow.h /Y C:\Tools\vcpkg\installed\x64-windows\include\lemon\

    C:\Python36-x64\python.exe -m pip install wheel cython
cache: C:\Tools\vcpkg\installed\x64-windows

before_build:
- cmd: >-

    C:\Python36-x64\python.exe -m pip wheel . -w dist --no-deps
    
    echo "pass"
           
    
test_script:
- cmd: >-

    C:\Python36-x64\python.exe -m pip install info_cluster --no-index -f dist

    rmdir /Q /S info_cluster
    
    C:\Python36-x64\python.exe -c "from info_cluster import psp; print(psp.__version__)"

    C:\Python36-x64\python.exe graph_cut_py_test.py
    
    C:\Python36-x64\python.exe -m twine upload dist/* -u zhaofeng-shu33 || ver>nul