version: 1.0.{build}
image: Visual Studio 2017
environment:
  TWINE_PASSWORD:
    secure: cDgJ0l9hLc0cTXODMVfjnA==
  VCPKG_ROOT: C:\Tools\vcpkg
  Python3_ROOT_DIR: C:\Python36-x64
install:
- cmd: >-

    git submodule update --init --recursive

    IF NOT EXIST "C:\Tools\vcpkg\installed\x64-windows\include\lemon\core.h" vcpkg install liblemon:x64-windows

    curl https://gitee.com/freewind201301/appveyor-patch-liblemon/raw/master/preflow.h -o preflow.h
    
    copy preflow.h /Y C:\Tools\vcpkg\installed\x64-windows\include\lemon\

    C:\Python36-x64\python.exe -m pip install wheel cython
    
    C:\Python37-x64\python.exe -m pip install wheel cython
    
cache: C:\Tools\vcpkg\installed\x64-windows
build: off
build_script:
- cmd: >-

    C:\Python36-x64\python.exe -m pip wheel . -w dist --no-deps
    
    C:\Python37-x64\python.exe -m pip wheel . -w dist --no-deps
               
deploy_script:
- cmd: >-
    
    C:\Python36-x64\python.exe -m twine upload dist/* -u zhaofeng-shu33 || ver>nul