version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x64
environment:
  VCPKG_ROOT: C:\Tools\vcpkg
  VCPKG_DEFAULT_TRIPLET: x64-windows-v141
install:
- cmd: >-

    git submodule update --init --recursive

    copy psp\x64-windows-v141.cmake C:\Tools\vcpkg\triplets\

    IF NOT EXIST "C:\Tools\vcpkg\installed\x64-windows-v141\include\boost\version.hpp" vcpkg install gtest:x64-windows-v141 boost-program-options:x64-windows-v141 boost-python:x64-windows-v141 liblemon:x64-windows-v141

    curl https://gitee.com/freewind201301/appveyor-patch-liblemon/raw/master/preflow.h -o preflow.h
    
    copy preflow.h /Y C:\Tools\vcpkg\installed\x64-windows-v141\include\lemon\

    C:\Python36-x64\python.exe -m pip install wheel scikit-learn six ete3 networkx
cache: C:\Tools\vcpkg\installed\x64-windows-v141

before_build:
- cmd: >-

    C:\Python36-x64\python.exe -m pip wheel . -w dist --no-deps
    
    echo "pass"
           
    
test_script:
- cmd: >-

    C:\Python36-x64\python.exe -m pip install info_cluster --no-index -f dist

    rmdir /Q /S info_cluster
    
    C:\Python36-x64\python.exe -c "from info_cluster import psp; print(psp.__version__)"

    C:\Python36-x64\python.exe graph_cut_py_test.py
    
    C:\Python36-x64\python.exe -m twine upload dist/* -u zhaofeng-shu33 || ver>nul